# Generated by Django 4.0.4 on 2022-05-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0002_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Online', 'Online')], default='Cash On Delivery', max_length=20),
        ),
    ]
